# Generated by Django 3.2 on 2022-06-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ranking2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='ranking3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='ranking4',
            field=models.IntegerField(default=0),
        ),
    ]
